### ISSUE TITLE
Only one object remains selected on run

### ISSUE THREAD

**Issue by noncom** [alelievr/HDRP-Custom-Passes#10]
Trying to run the Selection effect scene from the sample, **without changing anything at all**, in Unity 2019.3.0b6 results in that only one of the objects remains selected. When the scene is not running, all the three objects are selected in both the editor window and the scene view window:

not running:

![image](https://user-images.githubusercontent.com/2920144/67813229-141bce00-fab2-11e9-8b47-c45d81fca1d3.png)

running:

![image](https://user-images.githubusercontent.com/2920144/67813285-3ada0480-fab2-11e9-809c-f4efb5a9684b.png)

**Comment by alelievr** [comment]
Hello,
there is an issue in our object selection shader which discards objects that are too far away: It does not work with static batching in play mode, so we decided to cull based on pixel distance instead.

This is fixed on master
