### ISSUE TITLE
Minor SlightBlur.cs issue

### ISSUE THREAD

**Issue by jonaskew** [alelievr/HDRP-Custom-Passes#14]
If you exit Play Mode while the SlightBlur custom pass is active, you get a bunch of errors as the frame isn't released properly.

I noticed that in the Cleanup method the maskDepthBuffer.Release() wasn't checking that maskDepthBuffer wasn't null, and changing it to maskDepthBuffer?.Release() fixed the problem.

**Comment by alelievr** [comment]
Hello, I push the fix here: https://github.com/alelievr/HDRP-Custom-Passes/commit/c77aa4334126ddf347102cc246eec173a7178cfd
Thanks for the report :)
