### ISSUE TITLE
An error occurred while resolving packages

### ISSUE THREAD

**Issue by ethanfischer** [alelievr/HDRP-Custom-Passes#15]
I get this error when opening the freshly cloned project with the targeted unity version (2020.1.0a24). I also tried 2020.1.0b13 and 2019.3.10f1

![image](https://user-images.githubusercontent.com/6758736/85953864-2730b780-b939-11ea-967e-ef29225aa61e.png)

When I open the package manager, I see these errors:

![image](https://user-images.githubusercontent.com/6758736/85953975-c786dc00-b939-11ea-96a7-bd56d306b64e.png)

**Comment by ethanfischer** [comment]
I was able to resolve these by removing the offending packages, downloading High Definition Render Pipeline and updating Unity Collaborate

**Comment by alelievr** [comment]
Hey, thanks for reporting this issue.
I fixed the manifest of the project, it now uses standard HDRP 7.4.1 for 19.3 (https://github.com/alelievr/HDRP-Custom-Passes/commit/1dc3bc3154461d7f4a191ba5f2f4596de4cd5804)
