### ISSUE TITLE
Selection does not work on HDRP 8.2

### ISSUE THREAD

**Issue by WinDArt** [alelievr/HDRP-Custom-Passes#16]
Selection stopped working when switching to render pipelines high definition 8.2.0 Unity 2020.1.0f1. 
But works with HDRP 8.1 Unity 2020.1.0b2

**Comment by alelievr** [comment]
Hello, I upgraded the project to unity 2020.1 and HDRP 8.2.0, all the effects should not work correctly now.
Can you confirm that your issue is fixed?

**Comment by WinDArt** [comment]
> Hello, I upgraded the project to unity 2020.1 and HDRP 8.2.0, all the effects should not work correctly now.
> Can you confirm that your issue is fixed?
Selection works correctly.
Don't forget about set checkbox on Custom Pass
![image](https://user-images.githubusercontent.com/6035345/93133994-bea7da00-f6e0-11ea-945a-300e2474876f.png)
