### ISSUE TITLE
Some objects only get oulined in Editor depending on their shader

### ISSUE THREAD

**Issue by jcrombez** [alelievr/HDRP-Custom-Passes#18]
After i updated HDRP (not sure since which update, i'm using 7.4.3) some object are not outlined while playing in build mode.
It depends wich shader (built with Shader Graph) the object outlined is using.

Do you have any idea what a shader could do that would mess with the outline custom pass in build mode ?

**Comment by alelievr** [comment]
Not sure why it's happening 🤔 Are you using the selection code in this package or the outline custom pass [provided in the documentation](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.0/manual/Custom-Pass.html#scripting-example-outline-pass)?

Also, can you tell me which shader graphs are you using that work/doesn't work in the build?

**Comment by jcrombez** [comment]
Are you talking about this ? https://github.com/alelievr/HDRP-Custom-Passes/blob/master/Assets/CustomPasses/Selection/Shaders/02_Selection_Objects.shader (that's what i'm using)

The shader is from a shader graph based in the "Lit Master" node : 

![image](https://user-images.githubusercontent.com/777666/94173660-864c8c80-fe94-11ea-8b13-f6292232b277.png)

**Comment by alelievr** [comment]
Okay, I tried to repro the issue with this setup:

I created this shadergraph trying to match your settings:
![image](https://user-images.githubusercontent.com/6877923/94942756-026b5380-04d7-11eb-869c-ea31da2bdec4.png)

Created a sphere in the selection scene and applied this shader:
![image](https://user-images.githubusercontent.com/6877923/94942875-27f85d00-04d7-11eb-9f9d-867cda11413e.png)

And it works correctly in build (release):
![image](https://user-images.githubusercontent.com/6877923/94943189-93dac580-04d7-11eb-9abe-9b4db93b2a80.png)

Did I miss something in my setup?

**Comment by jcrombez** [comment]
Sorry for not answering you here, this was during the release period of the project, i had to drop this feature and then totally forgot about this issue.
I guess i'll see next time i need an outline effect if have more success with this :)

Thanks the help anyway !
