### ISSUE TITLE
Outline Shader not working as expected in VR

### ISSUE THREAD

**Issue by agandia** [alelievr/HDRP-Custom-Passes#19]
Hi,

I am using the outline effect to highlight the Objects that the VR character can pick up or interact with.
I imported the Custom pass volume and, the SelectionColor.cs script from your original project and set the glowing objects to the right layer. 

I see a double outline, one per eye.
The left eye looks correct, but for the right eye, the outline is displaced to the right of the actual object, creating a confusing effect.
![image](https://user-images.githubusercontent.com/47774226/91416928-59cf3180-e850-11ea-9663-19cb4a878b9a.png)

Any ideas on how to work around this?

Thank you!

**Comment by alelievr** [comment]
Fixed in this commit: c9d9859e55a71790a8490abe282e33fd01583de4
