### ISSUE TITLE
'GetSurfaceAndBuiltinData': output parameter 'surfaceData' not completely initialized error

### ISSUE THREAD

**Issue by tomekkie** [alelievr/HDRP-Custom-Passes#21]
How to fix this error?
'GetSurfaceAndBuiltinData': output parameter 'surfaceData' not completely initialized
in Unity 2020.2.1, Hdrp 10.2.2
I would be grateful for any help or update.

**Comment by tommy4421** [comment]
Want to know it too, I have the same issue.

**Comment by tommy4421** [comment]
Hmm.. adding `ZERO_INITIALIZE(SurfaceData, surfaceData);` in the GetSurfaceAndBuiltinData method seems to fix the problem

**Comment by alelievr** [comment]
Hello, for HDRP 10.x you can use the 2020.2 branch here: https://github.com/alelievr/HDRP-Custom-Passes/tree/2020.2

I'll merge it soon as the 2020.2 release is now official

**Comment by alelievr** [comment]
I merged the 2020.2 branch so now it's fixed in master
