### ISSUE TITLE
Outline with hdrp volumetrics not showing colors

### ISSUE THREAD

**Issue by dvanhaazel** [alelievr/HDRP-Custom-Passes#23]
Hi, I have an issue with the outline shader example (using unity 2020.2.5f1 ).
The outline is specified as red in the fullscreen pass, however it shows up black and only red when there's a density volume over it. So first thing I thought it's because of the volumetrics. But turning them off doesn't fix the issue as it remains black. I tried turning off everything one by one (also post effects), but it just stays black. Also tried different injection points, maybe you have any thoughts about this ? 
Thanks! 

![image](https://user-images.githubusercontent.com/8232926/110372521-ae006d00-804e-11eb-9886-6686c20e00b2.png)

![image](https://user-images.githubusercontent.com/8232926/110372999-4565c000-804f-11eb-8b11-8a155c4ca4f6.png)

**Comment by alelievr** [comment]
Hey, if you want the outline effect to be rendered without the fog, you can use the `AfterOpaqueAndSky` injection point:

![image](https://github.com/alelievr/HDRP-Custom-Passes/assets/6877923/3592b1c5-44d0-4fb4-a377-ab7d0d05676b)

This allows the fog to be applied on top of your outline effect and not the reverse
