### ISSUE TITLE
CopyBuffer from different Camera

### ISSUE THREAD

**Issue by ArieLeo** [alelievr/HDRP-Custom-Passes#36]
Is it possible to Copy Color buffer from different camera to be used for RenderTexture? 
using RenderFromCamera seems glitchy or is this a bug?

**Comment by alelievr** [comment]
RenderFromCamera only works for rendering specific buffers (depth, normal, motion vectors, etc.) from a separate point of view. Rendering the Lit color will not work as the lighting structures are shared with the main camera (or you need to render a view contained within the view of your main camera). 
To render lit scenes in a RenderTexture, currently, the only solution is to use multiple cameras but it has a very high performance cost.
