### ISSUE TITLE
Issues with motion vector for camera rotation

### ISSUE THREAD

**Issue by adepierre** [alelievr/HDRP-Custom-Passes#41]
Hello!

I've tried to run the CopyBuffer scene to see how motion vectors work. And there is something weird about them: when the camera is moving (translation), they seem to work correctly, with the objects being kind of visible in the motion vector display (picture 1). However, when the camera is simply looking around (no translation, rotation only), it seems that the objects don't appear (picture 2).

I'm not sure if this is just a misunderstanding of motion vectors from me or a real error, but any info about this matter would help me a lot!

Edit: I tried to copy the render texture to a normal texture in order to inspect the values using the following code, but it seems RGHalf is not the right format. The RenderTextureFormat is 29, which ... doesn't exist in the enum? 

```Csharp
RenderTexture.active = motionVectors;
Texture2D tex = new Texture2D(motionVectors.width, motionVectors.height,  TextureFormat.RGHalf, false);
tex.ReadPixels(new Rect(0, 0, motionVectors.width, motionVectors.height), 0, 0);
tex.Apply();
byte[] bytes = tex.EncodeToEXR(Texture2D.EXRFlags.CompressZIP);
System.IO.File.WriteAllBytes(path, bytes);
```

Camera translation:
![image](https://user-images.githubusercontent.com/24371370/159751830-0729df40-4b9f-4818-bf47-d8b04276aaf6.png)

Camera rotation only: 
![image](https://user-images.githubusercontent.com/24371370/159751297-9003fbc2-5223-4b0f-886c-eaefa97741db.png)

Unity: 2021.2.16f1
HDRP: 12.1.6

**Comment by HsiangYangChu** [comment]
Could you provide the complete code?

**Comment by adepierre** [comment]
What do you mean the complete code? I just ran the CopyBuffer scene from this repo with no modifications.

**Comment by alelievr** [comment]
I think this is expected, when you rotate the camera it doesn't change the position of objects in the camera relative space so the motion vector is only relative to the rotation of the camera in screen space
