### ISSUE TITLE
Question regarding "WRITE_NORMAL_BUFFER" in FPS Foreground

### ISSUE THREAD

**Issue by ArieLeo** [alelievr/HDRP-Custom-Passes#46]
Where is this keyword from, is this built in HDRP Keywords? Is there a place where i can see the build in HDRP Keywords?

**Comment by alelievr** [comment]
Yes it's an HDRP specific keyword. To have the complete list of keywords for a specific shader I'd suggest to look at the shader file directly (look for `#pragma shader_feature` and `#pragma multi_compile`): https://github.com/Unity-Technologies/Graphics/blob/master/Packages/com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader#L232
