### ISSUE TITLE
Decal Projector Get Through In Foreground

### ISSUE THREAD

**Issue by Shaun-Fong** [alelievr/HDRP-Custom-Passes#49]
I create a new hdrp project then copy all foreground asset.
using the default outdoorscene.
I really don't know what caused this to happen.
![1](https://user-images.githubusercontent.com/16713354/228164058-ef1030e3-5ade-4a93-b9c5-e81fa08331da.png)
this is first person view look like, decal projector through fpv object.
![2](https://user-images.githubusercontent.com/16713354/228164597-502cfd29-4fe6-4e37-9d9b-ee2398725363.png)
this is scene view look like.

**Comment by lookacat** [comment]
What did solve this issue

**Comment by Shaun-Fong** [comment]
> What did solve this issue

I never solve this issue(sad😭)
I switched to URP instead.
but still, decal is really f**king pain in fps...
and you have to avoid the weapon wall clipping、and also make sure the weapon scope effect works
oh scope effect will be affect by decal too......(I hate all these...)

**Comment by lookacat** [comment]
thx, yeah im debugging for hours now idk why its so much pain to just render a seperate layer in front of everything, but I have no idea of shaders and custom passes..
ill comment if i find a fix or a better solution

**Comment by Shaun-Fong** [comment]
> thx, yeah im debugging for hours now idk why its so much pain to just render a seperate layer in front of everything, but I have no idea of shaders and custom passes.. ill comment if i find a fix or a better solution

oh and post processing will be affect by those things too, like screen space AO.
 
actually, I have already solved these problems
[check this out ](https://assetstore.unity.com/packages/tools/camera/first-person-view-3-167950)
this plugin is for fpv(maybe the best way?idk) to avoid the weapon wall clipping, and post processing works just fine, shadow for weapons too(damn, those bad memories comes back. shadow and lighting is also big problem for weapon dual render method , that looks pretty bad in my opinion).
for scope effect i try to use custom render feature at the first time, but decal was gone 🤬
today I decide to use dual render(now performance issue come🤬 I just dont care anymore, F it)
I have been troubled by these critical issues since two years ago, and it wasn't until this year that they were all resolved, so much pain for somebody dont know graphics things, like me(noob
if you found better solution please let me know, good luck.

**Comment by lookacat** [comment]
thanks mate that works well.
