### ISSUE TITLE
Liquid custom pass not working in 2022.2 due to missing subgraph

### ISSUE THREAD

**Issue by gradeeterna** [alelievr/HDRP-Custom-Passes#50]
The liquid / metaball custom pass seems to be broken in 2022.2+ due to a missing subgraph called "SampleCustomBuffers". I've tried latest versions of 2022.2 and beta 9 which was used for last update of the project.

Thanks!

![liquidcustompass](https://user-images.githubusercontent.com/127218272/234366802-f2f5c17d-283f-4c25-ab7a-90b994dfb0c9.png)

**Comment by alelievr** [comment]
Thanks for the report, this issue was fixed here: https://github.com/alelievr/HDRP-Custom-Passes/commit/18469a9aacc966e5b0d6a527f86f08db88e032d8
