### ISSUE TITLE
Liquid not working on 2023.1.5f1

### ISSUE THREAD

**Issue by swPlumber42** [alelievr/HDRP-Custom-Passes#51]
Just tried to open the project in 2023.1.5f1.

The conversion has some problems with the Liquid.shadergraph that needs TargetSettings to HDRP.
But although I soved that problem, the custom pass draws black custom buffers (checked in the Frame Debugger)

I'm stuck. Please help.

**Comment by alelievr** [comment]
Hey, this issue should be fixed with this commit 94ee19b038c17085e782ff92e78a6efdcf81ceee, I checked in 2023.1.11f1 and it works on my side.
