### ISSUE TITLE
SeeThrough Question

### ISSUE THREAD

**Issue by infinite0007** [alelievr/HDRP-Custom-Passes#53]
When a layer mask is currently selected, this silhouette is drawn across all game objects. Is there currently no option to exclude or ignore this for one or more layers? That would create new possibilities.

one Example is that I can see through my Player the other one. which I don't want.
![image](https://github.com/alelievr/HDRP-Custom-Passes/assets/50872737/ed2888d5-7807-430e-8e14-3029e5b8c944)
Any simple solution?

**Comment by alelievr** [comment]
It may not be simple, but what you can do is use the stencil buffer to avoid rendering the outline on top of your character. The idea is to add a pass before the see-through passes that render only your character and write a value in the user stencil bits.
Then in the see-through pass, you can override the stencil tests to check if this bit is enabled and discard the pixel if it isn't.

Another solution without using the stencil is to use the same idea by rendering your character in a buffer (for example the custom color buffer) and then in the see-through ShaderGraph, check if the value of the custom color buffer is 0 or not, if it is you can clip the pixel with the alpha clipping option. Doing this is less performant than the stencil though but it'll probably not be an issue.
