### ISSUE TITLE
Show selection per object?

### ISSUE THREAD

**Issue by activey** [alelievr/HDRP-Custom-Passes#60]
Hi,

What would be the best way to control which object should be selected beside adding/removing it from Selection layer? ;)

Thanks

**Comment by alelievr** [comment]
Hello, 

You can use the [rendering layer masks](https://docs.unity3d.com/ScriptReference/Renderer-renderingLayerMask.html) as a filtering system in addition to the layer of the gameobjects. See this post on the forum for an example implementation: https://forum.unity.com/threads/custom-render-pass-custom-buffers.758558/#post-9678335
